module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#3525cd',
        'primary-container': '#4f46e5',
        'on-primary': '#ffffff',
        'on-primary-container': '#dad7ff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        secondary: '#4648d4',
        'secondary-container': '#6063ee',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'secondary-fixed-dim': '#c0c1ff',
        tertiary: '#7e3000',
        'tertiary-container': '#a44100',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffd2be',
        'tertiary-fixed-dim': '#ffb695',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0d1c2e',
        surface: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#ccdbf3',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d5e3fc',
        'surface-container-low': '#eff4ff',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d5e3fc',
        'surface-tint': '#4d44e3',
        'on-surface': '#0d1c2e',
        'on-surface-variant': '#464555',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#c3c0ff',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
      },
      fontFamily: {
        geist: ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        margin: '24px',
        gutter: '20px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      boxShadow: {
        soft: '0 1px 3px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
};
